// Module2_FrontendDev-Ragav/handson_08/src/components/CourseCard.vue
<script setup>
defineProps({
  name: String,
  code: String,
  credits: Number,
  grade: String,
})
</script>

<template>
  <article class="course-card">
    <div>
      <p class="code">{{ code }}</p>
      <h3>{{ name }}</h3>
    </div>
    <div class="details">
      <span>{{ credits }} credits</span>
      <strong>Grade: {{ grade }}</strong>
    </div>
  </article>
</template>

<style scoped>
.course-card {
  display: flex;
  justify-content: space-between;
  gap: 1rem;
  padding: 1rem;
  background: white;
  border: 1px solid #dbe3f0;
  border-radius: .5rem;
}

h3,
p {
  margin: 0;
}

.code {
  color: #526078;
  font-size: .85rem;
}

.details {
  display: grid;
  align-content: center;
  gap: .4rem;
  text-align: right;
}
</style>

// Module2_FrontendDev-Ragav/handson_10/react-app/src/components/CourseCard.jsx
export default function CourseCard({ course }) {
  return (
    <article style={{ border: '1px solid #dbe3f0', borderRadius: '0.5rem', padding: '1rem', background: 'white' }}>
      <p style={{ color: '#334155', margin: '0 0 0.25rem', fontSize: '0.85rem' }}>{course.code}</p>
      <h3 style={{ margin: '0 0 0.5rem' }}>{course.name}</h3>
      <div>
        <span>{course.credits} credits</span> <br />
        <strong>Grade: {course.grade}</strong>
      </div>
    </article>
  )
}
